# API 配置
api:
  host: "127.0.0.1"
  port: 8001
  title: "个人知识库智能助手"
  version: "0.1.0"

# LLM 配置
# llm:
#   provider: "openai"  # 或 "anthropic", "local" 等
#   model: "qwen-plus"
#   temperature: 0.7
#   max_tokens: 2000
#   api_key: "sk-aa9b02c4656649c5aa474f6dade4786b"

llm:
  provider: "local"
  # model : "/root/large_model_project/models/Qwen2.5-3B-Instruct"
  model : "/root/large_model_project/models/Qwen3-4B-Instruct-2507"
  temperature:  0.7
  max_tokens: 1024
  api_key: "none"
  base_url: "http://localhost:8000/v1"





# 向量数据库配置 (Milvus)
milvus:
  host: "localhost"
  port: 19530
  collection_name: "knowledge_base"
  # dimension: 768  # 向量维度，根据嵌入模型调整
  dimension: 384

# 文档数据库配置 (MongoDB)
mongodb:
  uri: "mongodb://localhost:27017"
  database: "personal_agent"
  collections:
    user_memory: "user_memories"
    conversation_history: "conversations"

# 嵌入模型配置
embedding:
  model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  device: "cpu"  # 或 "cuda"

# RAG 配置
rag:
  top_k: 5  # 检索 top K 个相关文档
  similarity_threshold: 0.8
  chunk_size: 500
  chunk_overlap: 50